version: "3"
services:
  mongodb:
    container_name: mongoDB
    build: ./mongoDB
    volumes:
      - mongo_vol:/usr/src/app/data/db.json
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3001:3000
    depends_on:
      - mongodb
      - api
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
volumes:
  mongo_vol: {}
