version: "3"
services:
  mongodb:
    image: mongodb
    container_name: mongodb
    build: ./mongoDB
    # ports:
    #   - 27018:27017
    volumes:
      - mongo_vol:/data/db
  api:
    build: ./api
    image: api
    container_name: api
    environment:
      - DB_NAME=viaScientificDB
      - MONGODB_URI=mongodb://mongodb:27017
    volumes:
      - ./api:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3001:3000
    depends_on:
      - mongodb
      - api
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
volumes:
  mongo_vol: {}
