import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={` ${inter.className}`}>
        <div className={`container max-w-[900px] mx-auto mt-20`}>{children}</div>
      </body>
    </html>
  );
}
